CREATE database HORARIOS;
USE HORARIOS;

CREATE TABLE PROFESOR(
IDPROFESOR INT(11),
APPATERNO VARCHAR(50),
APMATERNO VARCHAR(50),
NOMBRES VARCHAR(50),
NACIMIENTO date,
DIRECCION VARCHAR(200),
REFERENCIA VARCHAR(20),
GENERERO VARCHAR(1),
ESTADO VARCHAR(1) 
);

SELECT  * FROM PROFESOR;